# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example contra'
on:
  - workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["keyboards/maple_computing/minidox/rev1/"]'
      alphas: '["qwerty"]'
      nav: '["default"]'
      clipboard: '["win"]'
      layers: '["default"]'
      rules: '[
        "POINTING_DEVICE_ENABLE = yes",
        "POINTING_DEVICE_DRIVER = AZOTEQ_IQS5XX_TPS43",
        "BOOTLOADER = rp2040"
      ]'
      custom_config: '["default"]'
